package com.notificationpuller.storage

import org.json.JSONObject

/**
 * Persistent notification model used by the local file store.
 *
 * The ID is generated by the app and is independent of Android's
 * StatusBarNotification key. notificationKey remains unique per Android
 * notification so an updated notification can replace the existing record.
 */
data class LocalNotification(
    val id: String,
    val notificationKey: String,
    val packageName: String,
    val title: String,
    val text: String,
    val subText: String,
    val category: String,
    val timestamp: Long,
    val isOngoing: Boolean,
    val createdAt: Long
) {
    fun toJson(): JSONObject = JSONObject().apply {
        put("id", id)
        put("notificationKey", notificationKey)
        put("packageName", packageName)
        put("title", title)
        put("text", text)
        put("subText", subText)
        put("category", category)
        put("timestamp", timestamp)
        put("isOngoing", isOngoing)
        put("createdAt", createdAt)
    }

    companion object {
        fun fromJson(json: JSONObject): LocalNotification {
            return LocalNotification(
                id = json.optString("id"),
                notificationKey = json.optString("notificationKey"),
                packageName = json.optString("packageName"),
                title = json.optString("title"),
                text = json.optString("text"),
                subText = json.optString("subText"),
                category = json.optString("category"),
                timestamp = json.optLong("timestamp"),
                isOngoing = json.optBoolean("isOngoing", false),
                createdAt = json.optLong("createdAt")
            )
        }
    }
}
